#pragma once

#define SCREEN_WIDTH  720
#define SCREEN_HEIGHT 720

#define WALL_WIDTH   8
#define LEFT_WALL_X  SCREEN_WIDTH / 4
#define RIGHT_WALL_X SCREEN_WIDTH - LEFT_WALL_X - WALL_WIDTH

#define PLATFORM_WIDTH  50
#define PLATFORM_HEIGHT 5
#define PLATFORMS_SIZE  6
#define PLATFORM_MIN_X  LEFT_WALL_X + WALL_WIDTH
#define PLATFORM_MAX_X  RIGHT_WALL_X - PLATFORM_WIDTH
#define PLATFORM_MIN_Y_INCREMENT 120
#define PLATFORM_MAX_Y_INCREMENT 280

#define AIM_THICKNESS 1
#define AIM_SIZE      18
#define AIM_ANGLE_CAP 90.0f
#define AIM_SPEED     120.0f

#define FROG_WIDTH    64
#define FROG_HEIGHT   64
#define FROG_MAX_LIVES 3

#define SPAWN_POSITION_X SCREEN_WIDTH / 2 - FROG_WIDTH / 2
#define SPAWN_POSITION_Y 500

#define FEET_OFFSET_X 22
#define FEET_OFFSET_Y 35
#define FEET_WIDTH    22
#define FEET_HEIGHT    5

#define JUMP_POWER_CAP    400.0f
#define JUMP_POWER_SPEED  250.0f
#define GRAVITY 250.0f

#define IDLE       0
#define CHARGING   1
#define GOING_UP   2
#define GOING_DOWN 3

#define SCORE_X    20
#define SCORE_Y    20
#define SCORE_SIZE 20

#define GAME_OVER_TEXT_SIZE  50
#define PLAY_AGAIN_TEXT_SIZE 20

#define SCORE_TO_ADD_TEXT_SIZE  12
#define SCORE_TO_ADD_TEXT_SPEED 20
